services:
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "8081:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U docker -d blog" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - postgres

  server:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - postgres

volumes:
  db-data:

networks:
  postgres:
    driver: bridge
