services:
  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '8081:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U docker -d blog']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5432
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - postgres

  server:
    build: .
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - db
    networks:
      - postgres

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db-data:
  minio-data:

networks:
  postgres:
    driver: bridge
